### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by 01** [wictorwilen/botbuilder-teams-messagingextensions#4] opened 2019-05-07 03:27 UTC
First off wanted to thank you. Super exciting to see some activity on the botbuilder-teams front. 

I had a  few questions about this middleware as its similar to a solution I created (but didnt think to separate out the response body logic from response very clean solution) and wanted to fully understand everything before switching to utilizing it.

1.)  Was there a design decision not to wrap the ITeamsInvokeActivityHandler from the v4 SDK, my only concern would be consistencies between the sdk down the line 

2.) Saw references to multiple messaging extensions is this middleware designed for use case of having multiple extensions running through single app? Also I see that middleware short circuits for onSelectItem whats the reason for this? How does it interfere with the SDK

3.) The ability to filter on command line. What kind of use case is this for? Little confused is there a scenario where multiple  messaging extension invokes would have same commandId (onQuery, onFetch) or something like that

4.) Any context on when  onCardButtonClicked invoke is sent from teams extension.  Would this catch any Action Submit/ what would result in extensionSubmit invoke vs this one.

Thanks again! Excited to start utilizing this solution.

**Comment by wictorwilen** [comment] 2019-05-07 06:03
Hi @01 and thanks for the feedback!

1. The reason it is implemented this way, more of a botbuilder middleware than the current beta of `botbuilder-teams`, is due to the way the `botbuilder-teams` implemented their way of the activity processor (which in my opinion feels and looks like a clunky way of doing the event handling - I would have preferred a more botbuilder middleware approach) and how you need to shove all code into the bot implementation deeply nested in the activity processor. For instance if you're building a message extension, and not a bot, (which I think is a very common case) you're adding a lot of overhead using the activity processor from `botbuilder-teams`. 

2. Secondly, this was designed for the [Microsoft Teams Yeoman Generator](https://github.com/OfficeDev/generator-teams) and more specificallly to its hosting component [`express-msteams-host`](https://www.npmjs.com/package/express-msteams-host) - to make it easy to build message extensions and to be able to separate that logic out from the bot implementation and have a great way to support multiple message extensions (and easily add/remove those)

3. Almost same as above. Most invoke commands sends the `commandId` but unfortunately not `composeExtension/onCardButtonClicked` and `composeExtension/selectItem`. So when in the case that you have multiple message extensions you need to handle the case that this will be invoked for all your message extensions (using the same bot endpoint). And yes, this is only an issue where you have multiple message extensions for the same bot.

4). The `onCardButtonClick` reacts to the `composeExtension/onCardButtonClicked` which happens when you click on an `Action.Submit` action in a card in a conversation.

Great comments and questions, looking forward to more feedback!

**Closed** 2019-06-26 09:13 UTC
